add_newline = true

# Left side prompt
format = """
[╭─](bold green)$username $directory
[╰─❯](bold green) """

# Right side prompt
right_format = """$fill$git_branch$git_status$cmd_duration$python"""

[fill]
symbol = "."

[python]
format = '[(\($virtualenv\) )]($style)'
style = "yellow bold"

[directory]
style = "bold cyan"
truncate_to_repo = false

[git_branch]
symbol = " "

[git_status]
style = "bold yellow"

[cmd_duration]
min_time = 500
format = "took [$duration](bold yellow)"

[username]
show_always = true
style_user = "bold blue"
# Set to false or remove to hide hostname

[hostname]
disabled = true
