add_newline = true

format = """
[╭─](bold green)$username $directory$fill$git_branch$git_status$cmd_duration$python
[╰─❯](bold green) """


[fill]
symbol = "."
style = "bright-black"

[python]
format = '[(\($virtualenv\) )]($style)'
style = "yellow bold"

[directory]
style = "bold cyan"
truncate_to_repo = false

[git_branch]
symbol = " "
style = "cyan"

[git_status]
style = "red"

[cmd_duration]
min_time = 500
format = "took [$duration](bold yellow)"

[username]
show_always = true
style_user = "bold blue"
# Set to false or remove to hide hostname

[hostname]
disabled = true
