[ids]
*

[main]

backspace = noop

# Physical Escape is now your new Caps Lock that toggles the shift/symbol layer
esc = overload(control, toggle(caps_shift_layer))

leftalt = overload(alt, backspace)

rightalt = overload(altgr, enter)

capslock = overload(control, esc)

space = overload(shift, space)

[caps_shift_layer:S]
# Tapping the physical Escape key inside the layer turns it off and goes back to base
esc = toggle(caps_shift_layer)

capslock = toggle(caps_shift_layer)

# [altgr]
#
# h = left
# j = down
# k = up
# l = right
# e = home
# u = end
# a = pageup
# o = pagedown


