[ids]
*

[main]


esc = capslock

leftalt = overload(alt, backspace)

rightalt = overload(altgr, enter)

capslock = overload(control, esc)


# Space: tap = Space, hold = Shift
space = overload(shift, space)




